---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-pipelinedef2-sept11
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-pipelinedef2-sept11 
  name: test-pipelinedef2-sept11
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi